vocab_size: 50000
hidden_size: 768
layers: 12
heads: 12
max_position: 2048
padding_idx: 0
initializer_range: 0.02
scale_embeddings: false
freeze_embeddings: false
attention_dropout: 0.0
attention_bias: true
causal_attention: true
ffn_hidden_size: 3072
ffn_expansion_factor: 4.0
ffn_multiple_of: 256
ffn_activation: gelu
ffn_dropout: 0.0
ffn_bias: true
